export const EMPLOYEE_CREATE_REQ = 'EMPLOYEE_CREATE_REQ';
export const EMPLOYEE_CREATE_RES = 'EMPLOYEE_CREATE_RES';
export const EMPLOYEE_UPDATE_REQ = 'EMPLOYEE_UPDATE_REQ';
export const EMPLOYEE_UPDATE_RES = 'EMPLOYEE_UPDATE_RES';
export const USER_CREATE_REQ = 'USER_CREATE_REQ';
export const USER_CREATE_RES = 'USER_CREATE_RES';
